### ISSUE TITLE
'ADC_SIZE_10_BIT' was not declared in this scope

### ISSUE THREAD

**Issue by AnthoRdev** [giannivh/SmoothThermistor#2]
Hello,
Thanks for your library, that very helped me and cleaned my code.
But I have a problem with this line in my code (because i have to change the default value) :
`SmoothThermistor smoothThermistor(NTCPIN,ADC_SIZE_10_BIT,10000,10000,4080,25,10);`
The Arduino IDE return :
`'ADC_SIZE_10_BIT' was not declared in this scope`
Sorry for my poor english but if you have an idea for a solution, can you help me?
Anthony.

**Comment by giannivh** [comment]
I fixed the issue in 1.2.1. Please update SmoothThermistor. Be aware that it can take while for the Arduino guys to publish it.
